# Site settings
theme: freelancer-theme-jekyll
title: "Paddle to the Sea Oceanfront Cottages"
email: "paddletotheseacottages@gmail.com"
url: "https://paddletotheseacottages.com"
description: "Smith River, California oceanfront rentals."
keywords: "your keywords, separated by commas"
logo_width: 200
logo_height: 100
logo_image: "/assets/images/paddleboat.svg"
header_image: "/assets/images/beachlife.jpg"

favicon: "/assets/images/paddlefavicon.png"

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
social:
  - title: facebook-square
    url: https://www.facebook.com/paddletotheseacottages

properties:
 - title: 'The Bow'
   fickerurl: 'https://www.flickr.com/photos/158758305@N08/albums/72157669839538337'
   airbnbid: 27526763
   scrollid: bow
 - title: 'The Deck'
   fickerurl: 'https://www.flickr.com/photos/158758305@N08/albums/72157671996143768'
   airbnbid: 27115897
   scrollid: deck
 - title: 'The Stern'
   fickerurl: 'https://www.flickr.com/photos/158758305@N08/albums/72157696701339922'
   airbnbid: 27115289
   scrollid: stern

stylesheets:
 - 'https://fonts.googleapis.com/css?family=Satisfy'

# Analytics
analytics:
  provider               : "google-gtag"
  google:
    tracking_id          : "UA-123805982-1"
    anonymize_ip         : false

# Build settings
markdown: kramdown
permalink: pretty

webrick:
  headers:
    Content-Security-Policy: "frame-src https://www.airbnb.com/; font-src 'self' https://fonts.gstatic.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.airbnb.com; style-src 'self' https://fonts.googleapis.com 'unsafe-inline'; default-src 'self' https://www.google-analytics.com 'unsafe-inline'"
