# Site settings
theme: freelancer-theme-jekyll
title: "paddle to the sea oceanfront cottages"
email: "paddletotheseacottages@gmail.com"
url: "http://paddletotheseacottages.com"
description: "Smith River, California oceanfront rentals."
keywords: "your keywords, separated by commas"
logo_width: 200
logo_height: 100
logo_image: "/assets/images/paddleboat.svg"
header_image: "/assets/images/beachlife.jpg"

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:

# Build settings
markdown: kramdown
permalink: pretty
