source "https://rubygems.org"

gem "jekyll", "~> 3.8.3"
gem "freelancer-theme-jekyll"
gem "s3_website"

# Jekyll Assets
gem "sprockets", "~> 4.0.beta"
gem "uglifier"
gem "jekyll-assets", group: :jekyll_plugins

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.0" if Gem.win_platform?

